# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  lara5_joint1:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  lara5_joint2:
    has_velocity_limits: true
    max_velocity: 2.35
    has_acceleration_limits: false
    max_acceleration: 0
  lara5_joint3:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: false
    max_acceleration: 0
  lara5_joint4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  lara5_joint5:
    has_velocity_limits: true
    max_velocity: 2.56
    has_acceleration_limits: false
    max_acceleration: 0
  lara5_joint6:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
